version: "2"
run:
  timeout: 5m

formatters:
  enable:
    - gofumpt
    - golines
  settings:
    gofumpt:
      extra-rules: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - err113
    - errcheck
    - forbidigo
    - gochecknoglobals
    - gomodguard
    - nlreturn
    - noinlineerr
    - prealloc
    - revive
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    dupl:
      threshold: 180
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    mnd:
      ignored-numbers:
       - '2'
       - '0o666'
    predeclared:
      ignore:
        - new

issues:
  max-issues-per-linter: 0
  max-same-issues: 0