name: Integration Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "master"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: ./go.mod
      - name: Setup Cogent
        run: |
          sudo apt update
          sudo apt install -y gcc libgl1-mesa-dev libegl1-mesa-dev mesa-vulkan-drivers xorg-dev libwayland-dev libxkbcommon-dev
      - name: Build
        run: |
          go version
          go build -v .
      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout=5m --verbose          
